export const categoryDetails = {
  foundation: {
    label: "模型基础",
    why: "这些词描述模型处理信息时最基本的单位、表示与生成控制，是读懂产品文档和论文的共同语言。",
    steps: [["输入", "接收信息"], ["表示", "转换形式"], ["计算", "处理信息"], ["输出", "服务任务"]],
  },
  training: {
    label: "训练与优化",
    why: "训练方法决定模型学到什么、需要多少数据和计算，以及后续能否以较低成本适配新任务。",
    steps: [["数据", "准备样本"], ["学习", "更新参数"], ["验证", "检查效果"], ["迭代", "继续优化"]],
  },
  architecture: {
    label: "模型架构",
    why: "架构决定信息如何流动、计算如何分配，以及模型在速度、成本和能力上的上限。",
    steps: [["输入", "编码信息"], ["路由", "分配计算"], ["变换", "生成表示"], ["输出", "形成结果"]],
  },
  alignment: {
    label: "对齐与安全",
    why: "模型能力强不等于行为可靠；对齐与安全方法负责让输出更符合人类意图、规则和风险边界。",
    steps: [["识别", "发现风险"], ["约束", "应用规则"], ["评估", "检查行为"], ["改进", "减少偏差"]],
  },
  retrieval: {
    label: "检索与知识",
    why: "检索让模型使用外部、可更新和可引用的知识，是降低过时信息与无依据回答的重要路径。",
    steps: [["提问", "理解意图"], ["检索", "寻找证据"], ["排序", "筛选相关"], ["生成", "依据作答"]],
  },
  reasoning: {
    label: "推理与解码",
    why: "这类方法改变模型展开思考或选择下一个输出的方式，直接影响复杂任务的质量、速度和成本。",
    steps: [["问题", "理解目标"], ["展开", "生成候选"], ["比较", "检查路径"], ["输出", "选择结果"]],
  },
  multimodal: {
    label: "多模态",
    why: "多模态能力让 AI 在文字之外理解和生成图像、语音、视频与现实动作，扩大可服务的任务范围。",
    steps: [["感知", "读取模态"], ["对齐", "连接语义"], ["推理", "理解任务"], ["生成", "输出结果"]],
  },
  operations: {
    label: "智能体工程",
    why: "生产级智能体不仅需要模型能力，还需要流程、权限、可观测性和失败恢复来保证稳定交付。",
    steps: [["编排", "组织任务"], ["执行", "调用能力"], ["观察", "记录状态"], ["恢复", "处理异常"]],
  },
  evaluation: {
    label: "评测指标",
    why: "没有清晰的评测对象和指标，就无法判断模型是否真的进步，也无法比较质量、成本和风险。",
    steps: [["定义", "明确目标"], ["采样", "准备数据"], ["计算", "得到指标"], ["判断", "形成结论"]],
  },
};

export const glossarySources = [
  { label: "AI Beginner Guide 术语表", url: "https://yeasy.gitbook.io/ai_beginner_guide/fu-lu/appendix_a_glossary" },
  { label: "小码哥 AI 常见关键术语", url: "https://xmgtoagi.feishu.cn/wiki/RMvhwRiWuipHNNkjV7LcGVQZnFh" },
  { label: "Appen 人工智能专业术语表", url: "https://blog.csdn.net/Appen_China/article/details/114637332" },
  { label: "知乎 AI 大模型术语大全", url: "https://zhuanlan.zhihu.com/p/1973800325455554440" },
];

export const papersByCategory = {
  foundation: [
    { year: 2020, title: "Scaling Laws for Neural Language Models", venue: "arXiv", note: "解释模型规模、数据量与计算量之间的经验关系。", url: "https://arxiv.org/abs/2001.08361" },
    { year: 2017, title: "Attention Is All You Need", venue: "NeurIPS", note: "提出 Transformer，奠定现代大语言模型的基础架构。", url: "https://arxiv.org/abs/1706.03762" },
    { year: 2015, title: "Neural Machine Translation of Rare Words with Subword Units", venue: "ACL", note: "说明子词切分如何处理开放词表与稀有词。", url: "https://arxiv.org/abs/1508.07909" },
  ],
  training: [
    { year: 2023, title: "QLoRA: Efficient Finetuning of Quantized LLMs", venue: "NeurIPS", note: "把低比特量化与低秩适配结合，显著降低微调成本。", url: "https://arxiv.org/abs/2305.14314" },
    { year: 2022, title: "Training Compute-Optimal Large Language Models", venue: "NeurIPS", note: "研究模型参数与训练数据之间更有效的计算分配。", url: "https://arxiv.org/abs/2203.15556" },
    { year: 2021, title: "LoRA: Low-Rank Adaptation of Large Language Models", venue: "ICLR", note: "用低秩更新实现高效参数适配。", url: "https://arxiv.org/abs/2106.09685" },
  ],
  architecture: [
    { year: 2023, title: "Mamba: Linear-Time Sequence Modeling with Selective State Spaces", venue: "COLM", note: "探索 Transformer 之外的高效长序列架构。", url: "https://arxiv.org/abs/2312.00752" },
    { year: 2021, title: "On the Opportunities and Risks of Foundation Models", venue: "arXiv", note: "系统界定基础模型的能力、迁移方式与社会风险。", url: "https://arxiv.org/abs/2108.07258" },
    { year: 2021, title: "Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity", venue: "JMLR", note: "展示稀疏专家混合如何扩展模型容量。", url: "https://arxiv.org/abs/2101.03961" },
  ],
  alignment: [
    { year: 2023, title: "Direct Preference Optimization: Your Language Model is Secretly a Reward Model", venue: "NeurIPS", note: "提供无需显式奖励模型的偏好优化方法。", url: "https://arxiv.org/abs/2305.18290" },
    { year: 2022, title: "Constitutional AI: Harmlessness from AI Feedback", venue: "Anthropic", note: "用显式原则和 AI 反馈改进模型行为。", url: "https://arxiv.org/abs/2212.08073" },
    { year: 2022, title: "Training Language Models to Follow Instructions with Human Feedback", venue: "NeurIPS", note: "展示 RLHF 如何让模型更好地遵循用户意图。", url: "https://arxiv.org/abs/2203.02155" },
  ],
  retrieval: [
    { year: 2020, title: "ColBERT: Efficient and Effective Passage Search via Contextualized Late Interaction", venue: "SIGIR", note: "用后期交互在检索质量与效率之间取得平衡。", url: "https://arxiv.org/abs/2004.12832" },
    { year: 2020, title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks", venue: "NeurIPS", note: "奠定检索证据并结合生成模型作答的经典范式。", url: "https://arxiv.org/abs/2005.11401" },
    { year: 2020, title: "Dense Passage Retrieval for Open-Domain Question Answering", venue: "EMNLP", note: "用稠密向量表示实现开放域文档检索。", url: "https://arxiv.org/abs/2004.04906" },
  ],
  reasoning: [
    { year: 2023, title: "Tree of Thoughts: Deliberate Problem Solving with Large Language Models", venue: "NeurIPS", note: "把单一路径推理扩展为可搜索和回退的思维树。", url: "https://arxiv.org/abs/2305.10601" },
    { year: 2022, title: "Self-Consistency Improves Chain of Thought Reasoning in Language Models", venue: "ICLR", note: "通过多路径采样与一致性投票提高推理可靠性。", url: "https://arxiv.org/abs/2203.11171" },
    { year: 2022, title: "Chain-of-Thought Prompting Elicits Reasoning in Large Language Models", venue: "NeurIPS", note: "证明中间推理步骤能提升复杂问题表现。", url: "https://arxiv.org/abs/2201.11903" },
  ],
  multimodal: [
    { year: 2023, title: "Visual Instruction Tuning", venue: "NeurIPS", note: "以视觉指令数据训练通用视觉语言助手。", url: "https://arxiv.org/abs/2304.08485" },
    { year: 2022, title: "Flamingo: a Visual Language Model for Few-Shot Learning", venue: "NeurIPS", note: "展示图像与文本交错输入下的少样本多模态学习。", url: "https://arxiv.org/abs/2204.14198" },
    { year: 2021, title: "Learning Transferable Visual Models From Natural Language Supervision", venue: "ICML", note: "用大规模图文对齐学习通用视觉表示。", url: "https://arxiv.org/abs/2103.00020" },
  ],
  operations: [
    { year: 2024, title: "τ-bench: A Benchmark for Tool-Agent-User Interaction", venue: "arXiv", note: "评测工具、规则和用户共同参与的真实业务任务。", url: "https://arxiv.org/abs/2406.12045" },
    { year: 2024, title: "SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering", venue: "NeurIPS", note: "说明接口设计与执行环境如何影响智能体表现。", url: "https://arxiv.org/abs/2405.15793" },
    { year: 2023, title: "AgentBench: Evaluating LLMs as Agents", venue: "ICLR", note: "在多种交互环境中系统评估智能体能力。", url: "https://arxiv.org/abs/2308.03688" },
  ],
  evaluation: [
    { year: 2022, title: "Holistic Evaluation of Language Models", venue: "TMLR", note: "从准确性、鲁棒性、公平性与效率等维度综合评测模型。", url: "https://arxiv.org/abs/2211.09110" },
    { year: 2022, title: "Beyond the Imitation Game: Quantifying and Extrapolating the Capabilities of Language Models", venue: "TMLR", note: "通过 BIG-bench 衡量模型在大量不同任务上的能力。", url: "https://arxiv.org/abs/2206.04615" },
    { year: 2021, title: "TruthfulQA: Measuring How Models Mimic Human Falsehoods", venue: "ACL", note: "专门衡量模型是否生成看似合理但错误的回答。", url: "https://arxiv.org/abs/2109.07958" },
  ],
};

const rawEntries = [
  ["agent", "Agent", "智能体", "以目标为导向，能观察环境、做出决策并采取行动的 AI 系统。", "适合需要多步骤推进、调用工具或持续反馈的任务。", "聊天模型给答案，智能体还会继续把事情做下去。", ["ai agent", "代理"], "operations"],
  ["token", "Token", "词元", "模型读取和生成文本时使用的基本单位，可能是一个字、词的一部分或标点。", "用于计算上下文长度、调用成本和生成上限。", "Token 不等于字数；同一句话在不同分词器里数量会不同。", ["tokens", "令牌", "标记"], "foundation"],
  ["tokenizer", "Tokenizer", "分词器", "把原始文本切分并映射成 token 编号的组件。", "模型输入前编码文本，输出后再还原成人类可读文字。", "模型并不直接看文字，而是看分词器生成的数字序列。", ["tokenization", "分词", "词元化"], "foundation"],
  ["vocabulary", "Vocabulary", "词表", "分词器能够识别和生成的全部 token 集合。", "决定文本如何被切分，以及特殊符号如何表示。", "词表越大不一定越好，还要权衡序列长度与参数成本。", ["vocab", "词汇表"], "foundation"],
  ["embedding", "Embedding", "向量嵌入", "把 token、图片或其他对象转换成可计算的稠密向量表示。", "用于语义搜索、聚类、推荐和模型内部表示。", "语义相近的对象通常在向量空间中更接近。", ["embeddings", "嵌入", "向量"], "foundation"],
  ["latent-space", "Latent space", "潜在空间", "模型在内部用连续向量表示抽象特征的空间。", "用于生成、编辑、聚类或理解高维数据结构。", "它不是现实空间，而是模型学到的特征坐标系。", ["latent", "潜空间"], "foundation"],
  ["parameter", "Parameter", "模型参数", "训练过程中被学习并决定模型行为的数值权重。", "常用参数量描述模型规模和存储需求。", "参数是模型学到的内容，超参数则由训练者设定。", ["parameters", "权重", "参数"], "foundation"],
  ["hyperparameter", "Hyperparameter", "超参数", "训练前或训练过程中人为设定、而不是由模型直接学出的配置。", "包括学习率、批大小、层数和采样温度等。", "它控制学习过程，但本身通常不是模型权重。", ["hyperparameters", "超参"], "foundation"],
  ["checkpoint", "Checkpoint", "模型检查点", "训练到某一时刻保存下来的模型参数与状态快照。", "用于继续训练、回滚、比较或部署特定版本。", "同一模型名称可能对应多个能力不同的检查点。", ["model checkpoint", "检查点"], "foundation"],
  ["transformer", "Transformer", "Transformer 架构", "以注意力机制为核心、能够并行处理序列信息的神经网络架构。", "是现代大语言模型和大量视觉模型的基础。", "它用注意力直接建立序列中不同位置的关系。", ["变换器", "transformer架构"], "foundation"],
  ["attention", "Attention", "注意力机制", "让模型动态判断输入中哪些部分对当前计算最重要的机制。", "用于连接远距离信息并聚合相关上下文。", "注意力是一种加权读取方式，不等同于人类注意力。", ["注意力"], "foundation"],
  ["self-attention", "Self-attention", "自注意力", "让同一序列中的每个位置读取并组合其他位置的信息。", "用于理解词与词、图块与图块之间的关系。", "输入内部彼此关注叫自注意力，读取另一序列叫交叉注意力。", ["self attention", "自注意力机制"], "foundation"],
  ["cross-attention", "Cross-attention", "交叉注意力", "让一组表示从另一组表示中选择和读取相关信息。", "常用于文本指导图像生成或解码器读取编码结果。", "它连接两个信息源，而不是只在同一序列内部计算。", ["cross attention", "交叉注意力机制"], "foundation"],
  ["positional-encoding", "Positional encoding", "位置编码", "向模型注入 token 顺序或空间位置的信息。", "帮助注意力架构区分先后顺序和相对距离。", "注意力本身不天然知道顺序，位置编码补上这部分。", ["position embedding", "位置嵌入", "位置编码"], "foundation"],
  ["context-window", "Context window", "上下文窗口", "一次推理中模型能够接收和生成的 token 总范围。", "决定一轮任务能同时放入多少指令、资料和历史。", "窗口更长不代表模型能同样好地利用每一处信息。", ["context length", "上下文长度", "上下文"], "foundation"],
  ["prompt", "Prompt", "提示词", "发送给模型、用于描述任务和提供上下文的输入。", "用于指定目标、格式、角色、示例和约束。", "好提示词减少歧义，但不能替代可靠的数据和系统设计。", ["提示", "提示语"], "foundation"],
  ["system-prompt", "System prompt", "系统提示词", "由应用在对话开始时提供、优先级通常高于用户消息的指令。", "用于规定角色、行为边界、工具和输出约束。", "它是运行时指令，不是模型参数，也不是绝对安全边界。", ["system message", "系统消息", "系统指令"], "foundation"],
  ["completion", "Completion", "模型补全", "模型根据已有输入继续预测并生成后续 token 的结果。", "用于文本生成、代码补全和对话回复。", "大语言模型的核心动作始终是预测下一个 token。", ["text completion", "补全", "续写"], "foundation"],
  ["inference", "Inference", "模型推理", "训练完成后，模型根据新输入计算并生成结果的阶段。", "用于线上回答、分类、生成和智能体决策。", "训练在更新参数，推理通常只使用参数。", ["推理", "模型推理阶段"], "foundation"],
  ["logit", "Logit", "逻辑值", "模型在归一化前对每个候选 token 给出的原始分数。", "用于计算概率、应用温度或进行受限解码。", "Logit 不是概率；经过 softmax 后才形成概率分布。", ["logits", "原始分数"], "foundation"],
  ["softmax", "Softmax", "Softmax 函数", "把一组任意分数转换为总和为 1 的概率分布。", "常用于把 token logits 转换为下一词概率。", "它会放大相对高分项，但不会判断内容是否正确。", ["归一化指数函数"], "foundation"],
  ["temperature", "Temperature", "采样温度", "在生成时调整概率分布尖锐程度的参数。", "控制输出更稳定还是更发散。", "温度低更确定，温度高更多样，但不是创造力按钮。", ["温度", "生成温度"], "foundation"],
  ["top-k-sampling", "Top-k sampling", "Top-k 采样", "每一步只保留概率最高的 k 个 token 再进行采样。", "用于限制低概率词进入生成结果。", "k 固定候选数量，不考虑这些候选累计占多少概率。", ["top k", "top-k", "前k采样"], "foundation"],
  ["top-p-sampling", "Top-p sampling", "Top-p 采样", "保留累计概率达到 p 的最小 token 集合再采样。", "用于让候选数量随模型置信度动态变化。", "Top-p 控制概率质量，Top-k 控制候选数量。", ["nucleus sampling", "top p", "核采样"], "foundation"],
  ["perplexity", "Perplexity", "困惑度", "衡量语言模型对一段文本预测不确定性的指标。", "常用于比较同类语言模型或训练过程。", "数值越低通常预测越好，但不直接等于真实任务体验。", ["ppl", "困惑度指标"], "foundation"],

  ["pretraining", "Pretraining", "预训练", "在大规模通用数据上学习基础模式和知识的训练阶段。", "用于获得可迁移到许多下游任务的基础模型。", "预训练学通用能力，微调再适应具体任务。", ["pre-training", "预训练阶段"], "training"],
  ["fine-tuning", "Fine-tuning", "微调", "在已有模型上用较小的专用数据继续训练。", "用于适配领域、风格、任务或行为偏好。", "微调会改变参数，提示词只改变当前上下文。", ["finetuning", "fine tuning", "微调训练"], "training"],
  ["sft", "Supervised fine-tuning", "监督微调", "用输入与目标输出成对的数据训练模型遵循示例。", "常用于把预训练模型变成可对话、可执行指令的助手。", "SFT 模仿示范答案，不直接比较哪个答案更受偏好。", ["supervised fine tuning", "监督式微调"], "training"],
  ["instruction-tuning", "Instruction tuning", "指令微调", "用覆盖多种任务的指令—回答数据训练模型理解自然语言任务。", "用于提升零样本和跨任务的指令遵循能力。", "它关注任务表达的泛化，而不只是单一领域适配。", ["instruction fine-tuning", "指令调优"], "training"],
  ["lora", "LoRA", "低秩适配", "冻结大部分模型参数，只训练少量低秩矩阵的高效微调方法。", "适合低成本训练多个领域或角色适配器。", "它减少可训练参数，不会自动减少推理所需的基础模型。", ["low-rank adaptation", "低秩微调"], "training"],
  ["peft", "PEFT", "参数高效微调", "只更新模型一小部分参数或新增轻量模块的微调方法总称。", "用于降低显存、存储和多任务适配成本。", "LoRA 是 PEFT 的一种，而不是两套并列概念。", ["parameter-efficient fine-tuning", "高效微调"], "training"],
  ["distillation", "Knowledge distillation", "知识蒸馏", "让较小的学生模型学习较大教师模型输出或中间表示的方法。", "用于压缩模型、降低延迟或迁移能力。", "学生学的是教师行为分布，不是简单复制参数。", ["model distillation", "蒸馏", "知识蒸馏"], "training"],
  ["quantization", "Quantization", "模型量化", "用更低精度数值表示权重或激活，以减少内存和计算。", "用于在有限硬件上部署更大模型或提高吞吐。", "量化节省资源，但精度过低可能损失质量。", ["模型量化", "低比特量化"], "training"],
  ["pruning", "Pruning", "模型剪枝", "移除影响较小的权重、通道或结构，以减小模型。", "用于压缩、加速或构建稀疏模型。", "剪枝删掉连接，量化则降低数值精度。", ["model pruning", "剪枝"], "training"],
  ["gradient-descent", "Gradient descent", "梯度下降", "沿着损失函数下降方向迭代更新参数的优化思想。", "用于训练神经网络最小化预测误差。", "梯度告诉方向，优化器决定具体怎么走。", ["梯度下降法", "gd"], "training"],
  ["backpropagation", "Backpropagation", "反向传播", "从输出误差向前逐层计算参数梯度的算法。", "用于高效获得神经网络中每个参数的更新信号。", "反向传播算梯度，优化器使用梯度更新参数。", ["backprop", "反传", "反向传播算法"], "training"],
  ["loss-function", "Loss function", "损失函数", "把模型预测与训练目标的差异转换为可优化数值的函数。", "用于定义模型在训练中应该改进什么。", "指标用于评价，损失用于驱动学习；两者不一定相同。", ["objective function", "损失", "目标函数"], "training"],
  ["optimizer", "Optimizer", "优化器", "根据梯度和内部状态决定参数更新幅度与方向的算法。", "用于控制训练收敛速度与稳定性。", "Adam、SGD 是优化器，学习率是它们的重要配置。", ["优化算法", "优化器算法"], "training"],
  ["learning-rate", "Learning rate", "学习率", "控制每次参数更新步长大小的超参数。", "用于平衡收敛速度和训练稳定性。", "过大可能震荡，过小可能学习太慢或停在次优位置。", ["lr", "学习速率"], "training"],
  ["batch", "Batch", "批次", "一次参数更新中同时处理的一组训练样本。", "用于提高并行效率并稳定梯度估计。", "Batch size 是样本数，不是训练轮数。", ["batch size", "批大小", "训练批次"], "training"],
  ["epoch", "Epoch", "训练轮次", "模型完整遍历一次训练数据集的过程。", "用于描述训练进行了多少轮。", "一个 epoch 包含多个 batch 更新。", ["epochs", "轮", "训练周期"], "training"],
  ["curriculum-learning", "Curriculum learning", "课程学习", "按难度或能力依赖逐步安排训练样本的方法。", "用于让模型先掌握基础模式再学习复杂任务。", "关键在样本顺序，不只是增加更多数据。", ["课程式学习"], "training"],
  ["continual-learning", "Continual learning", "持续学习", "让模型在不断到来的新数据或任务上继续学习，同时尽量保留旧能力。", "用于长期适应变化环境和用户需求。", "难点不是学新知识，而是不忘旧知识。", ["continuous learning", "终身学习", "增量学习"], "training"],
  ["catastrophic-forgetting", "Catastrophic forgetting", "灾难性遗忘", "模型学习新任务后，原有任务能力显著下降的现象。", "用于诊断持续学习和领域微调的副作用。", "它不是正常小幅波动，而是旧能力被新更新覆盖。", ["灾难遗忘", "灾难性遗忘问题"], "training"],
  ["active-learning", "Active learning", "主动学习", "模型主动挑选最值得标注的样本，以减少人工标注量。", "适合标注昂贵、未标注数据充足的任务。", "重点是选择信息量高的样本，不是自动生成标签。", ["主动式学习"], "training"],
  ["synthetic-data", "Synthetic data", "合成数据", "由模型、模拟器或规则生成，而不是直接采集自真实世界的数据。", "用于扩充稀缺场景、隐私保护或构造可控训练样本。", "合成数据可扩规模，但也会复制生成器的偏差和错误。", ["generated data", "生成数据"], "training"],
  ["data-curation", "Data curation", "数据策展", "对训练数据进行筛选、去重、清洗、平衡和组织的过程。", "用于提高数据质量并控制模型学到的分布。", "数据多不等于数据好，选择标准本身就是模型设计。", ["数据整理", "数据筛选"], "training"],
  ["data-labeling", "Data labeling", "数据标注", "为样本添加类别、边界、答案或偏好等监督信号。", "用于监督训练、评测集和人类反馈数据。", "标签质量与一致性往往比标注数量更关键。", ["data annotation", "数据注释", "标注"], "training"],
  ["data-augmentation", "Data augmentation", "数据增强", "通过变换或生成新样本扩大训练数据多样性。", "用于提升泛化、鲁棒性并缓解数据不足。", "有效增强应保留任务语义，而不是制造错误标签。", ["数据扩增", "样本增强"], "training"],
  ["transfer-learning", "Transfer learning", "迁移学习", "把一个任务或大数据集学到的表示迁移到另一个任务。", "用于减少新任务所需的数据和训练成本。", "预训练加微调就是迁移学习的典型形式。", ["迁移式学习"], "training"],

  ["llm", "Large language model", "大语言模型", "在大规模文本上训练、能够理解和生成语言的参数化模型。", "用于对话、写作、代码、检索增强和智能体决策。", "LLM 是模型类型，Agent 是围绕模型组织行动的系统。", ["large language model", "大模型", "语言大模型"], "architecture"],
  ["foundation-model", "Foundation model", "基础模型", "在广泛数据上训练、可适配许多下游任务的大规模通用模型。", "作为微调、提示和应用开发的能力底座。", "基础模型强调可迁移性，不只强调参数规模。", ["foundation models", "基座模型"], "architecture"],
  ["slm", "Small language model", "小语言模型", "参数量和计算需求较小、通常面向效率或特定场景的语言模型。", "适合端侧、低延迟、隐私敏感或高并发部署。", "小不代表弱；在明确任务上可能更划算。", ["small language model", "小模型"], "architecture"],
  ["multimodal-model", "Multimodal model", "多模态模型", "能够处理或生成文字、图像、语音、视频等多种数据形式的模型。", "用于看图问答、语音交互、视频理解和内容生成。", "关键不是输入类型多，而是不同模态能在同一任务中协同。", ["multimodal llm", "多模态大模型"], "architecture"],
  ["vlm", "Vision-language model", "视觉语言模型", "联合理解图像与文本并在两者之间建立语义联系的模型。", "用于图片问答、视觉检索、OCR 后理解和界面操作。", "VLM 关注视觉与语言，不一定具备动作执行能力。", ["vision language model", "视觉语言大模型"], "architecture"],
  ["autoregressive-model", "Autoregressive model", "自回归模型", "按顺序根据之前的内容预测下一个元素的模型。", "用于大多数文本生成和部分图像、音频生成。", "它一次向前生成，前面错误可能影响后续。", ["autoregressive", "自回归"], "architecture"],
  ["encoder", "Encoder", "编码器", "把输入转换为内部表示、供后续任务读取的模型组件。", "用于理解、检索、分类或为解码器提供上下文。", "编码器负责表示输入，通常不直接逐词生成长输出。", ["编码器模型"], "architecture"],
  ["decoder", "Decoder", "解码器", "根据已有表示和已生成内容逐步产生输出的模型组件。", "用于文本、图像或语音生成。", "现代 LLM 多为仅解码器架构，但解码器也可读取编码器结果。", ["解码器模型"], "architecture"],
  ["encoder-decoder", "Encoder-decoder", "编码器—解码器", "先编码输入，再由解码器基于编码结果生成输出的架构。", "常用于翻译、摘要和输入输出结构不同的任务。", "它把理解输入与生成输出分成两个阶段。", ["encoder decoder", "编解码器", "编码解码架构"], "architecture"],
  ["moe", "Mixture of experts", "专家混合模型", "每次输入只激活多个专家子网络中的一部分的稀疏架构。", "用于在不同比例增加计算的情况下扩大模型容量。", "总参数很多，但单次推理只使用其中一部分。", ["mixture-of-experts", "专家混合", "混合专家"], "architecture"],
  ["expert-routing", "Expert routing", "专家路由", "在专家混合模型中决定每个 token 应交给哪些专家处理的机制。", "用于平衡专业化、计算效率和负载。", "路由错误或不均会让部分专家过载、部分闲置。", ["moe routing", "路由器", "专家选择"], "architecture"],
  ["sparse-model", "Sparse model", "稀疏模型", "只有部分参数、连接或计算路径在一次处理时被激活的模型。", "用于降低计算或扩大可用容量。", "稀疏描述激活方式，不等同于模型规模小。", ["sparsity", "稀疏架构"], "architecture"],
  ["diffusion-model", "Diffusion model", "扩散模型", "学习逐步去除噪声、把随机信号还原为数据的生成模型。", "广泛用于图像、视频、音频和三维内容生成。", "它通常通过多步去噪生成，不是逐 token 续写。", ["diffusion", "扩散生成模型"], "architecture"],
  ["diffusion-language-model", "Diffusion language model", "扩散语言模型", "用迭代去噪或掩码修复方式生成文本的语言模型。", "用于探索并行生成、全局修订和不同于自回归的解码方式。", "它可以反复修改整段文本，而不只从左到右追加。", ["diffusion lm", "dLLM", "扩散式语言模型"], "architecture"],
  ["world-model", "World model", "世界模型", "学习环境状态、变化规律和行动后果的内部预测模型。", "用于规划、模拟、机器人和可交互内容生成。", "它预测世界如何变化，不只是生成描述世界的文字。", ["world models", "环境模型"], "architecture"],
  ["reasoning-model", "Reasoning model", "推理模型", "专门优化复杂问题分解、计算、验证和多步决策能力的模型。", "用于数学、代码、科学和长链任务。", "标签通常描述训练与使用方式，不代表模型真的像人一样思考。", ["reasoning llm", "推理大模型"], "architecture"],
  ["reward-model", "Reward model", "奖励模型", "根据人类或规则偏好给候选输出打分的模型。", "用于 RLHF、候选排序和行为评估。", "它学习什么更受偏好，不一定判断事实真伪。", ["rm", "奖励函数模型"], "architecture"],
  ["critic-model", "Critic model", "批评模型", "专门检查生成结果、指出问题或提供改进意见的模型。", "用于自我修正、代码审查和智能体反思。", "Critic 提供反馈，Verifier 更强调可比较的验证信号。", ["critic", "评论模型", "评审模型"], "architecture"],
  ["sequence-to-sequence", "Sequence-to-sequence", "序列到序列", "把一个可变长度序列映射为另一个可变长度序列的建模方式。", "用于翻译、摘要、语音识别和格式转换。", "它描述输入输出形式，不限定内部一定使用哪种架构。", ["seq2seq", "序列映射"], "architecture"],
  ["state-space-model", "State space model", "状态空间模型", "用隐藏状态随序列更新来建模长期依赖的架构家族。", "用于高效处理长序列并探索注意力之外的方案。", "它以递推状态压缩历史，而不是显式比较所有 token 对。", ["ssm", "状态空间架构"], "architecture"],
  ["mamba", "Mamba", "Mamba 架构", "使用选择性状态空间机制、以线性复杂度处理序列的模型架构。", "用于长文本、语音、视觉和时间序列建模。", "Mamba 是状态空间模型的一种，不是所有 SSM 的统称。", ["mamba model", "选择性状态空间模型"], "architecture"],

  ["alignment", "AI alignment", "AI 对齐", "让 AI 的目标和行为与人类意图、价值和规则尽量一致的研究与工程问题。", "用于训练、部署和治理高能力模型。", "对齐不是单一算法，而是一组目标、方法和评测。", ["alignment", "人工智能对齐", "模型对齐"], "alignment"],
  ["rlhf", "RLHF", "人类反馈强化学习", "利用人类偏好训练奖励信号，再通过强化学习优化模型的方法。", "用于提升指令遵循、有用性和安全性。", "它优化人类偏好，不保证输出事实完全正确。", ["reinforcement learning from human feedback", "人类反馈强化学习"], "alignment"],
  ["rlaif", "RLAIF", "AI 反馈强化学习", "用 AI 模型产生或判断偏好信号，再训练目标模型的方法。", "用于降低人类标注成本并扩大反馈规模。", "反馈来自 AI，因此会继承评审模型的盲点。", ["reinforcement learning from ai feedback", "人工智能反馈强化学习"], "alignment"],
  ["dpo", "Direct preference optimization", "直接偏好优化", "直接用偏好对训练模型，无需单独训练奖励模型和运行强化学习。", "用于更简单稳定地学习“更喜欢哪个回答”。", "DPO 仍需要高质量偏好数据，只是优化流程更直接。", ["direct preference optimization", "直接偏好优化"], "alignment"],
  ["ppo", "Proximal policy optimization", "近端策略优化", "限制每次策略更新幅度的强化学习算法。", "常用于 RLHF 中根据奖励模型调整语言模型。", "PPO 是通用 RL 算法，RLHF 是使用它的一种场景。", ["proximal policy optimization", "近端策略优化算法"], "alignment"],
  ["grpo", "Group relative policy optimization", "组相对策略优化", "用同一问题的一组候选结果相互比较来构造优势信号的强化学习方法。", "用于降低对独立价值模型的依赖并训练推理行为。", "它按组内相对表现学习，而不是只看单个绝对分数。", ["group relative policy optimization", "组相对策略优化"], "alignment"],
  ["constitutional-ai", "Constitutional AI", "宪法式 AI", "用一组显式原则指导模型自我批评、修订和偏好学习的方法。", "用于让安全标准更可描述和规模化。", "这里的“宪法”是行为原则集合，不是法律文件。", ["cai", "constitutional alignment", "宪法式人工智能"], "alignment"],
  ["safety-alignment", "Safety alignment", "安全对齐", "专门减少危险、越权或有害行为的对齐工作。", "用于拒答策略、风险识别、工具权限和高风险场景控制。", "安全对齐是整体对齐的一部分，不等于所有产品规则。", ["安全性对齐", "模型安全对齐"], "alignment"],
  ["red-teaming", "Red teaming", "红队测试", "主动设计攻击、边界和异常场景来寻找系统弱点。", "用于发现越狱、数据泄露、工具滥用和策略绕过。", "红队的目标是暴露问题，不是证明系统绝对安全。", ["red team", "红队评测", "红队攻击"], "alignment"],
  ["hallucination", "Hallucination", "幻觉", "模型生成流畅但缺乏依据、与事实或输入不一致的内容。", "用于描述知识回答、摘要和工具结果中的可信度问题。", "幻觉不是模型“看见”了什么，而是无可靠支撑的生成。", ["model hallucination", "模型幻觉"], "alignment"],
  ["grounding", "Grounding", "依据约束", "让模型回答明确依赖可观察输入、检索证据或环境状态。", "用于减少无依据生成并提升可验证性。", "Grounding 提供依据，但依据本身仍可能错误或过时。", ["grounded generation", "事实依据", "落地"], "alignment"],
  ["calibration", "Calibration", "置信度校准", "让模型表达的置信度与实际正确率尽量一致。", "用于风险分级、拒答、人工升级和候选选择。", "高置信不等于正确；校准关注两者是否匹配。", ["confidence calibration", "模型校准"], "alignment"],
  ["interpretability", "Interpretability", "可解释性", "理解模型为何做出某个预测或内部学到了什么的能力与方法。", "用于调试、信任、安全研究和科学分析。", "解释可以描述行为，也可以研究内部机制，层级不同。", ["explainability", "可解释人工智能", "xai"], "alignment"],
  ["mechanistic-interpretability", "Mechanistic interpretability", "机制可解释性", "通过神经元、注意力头和计算回路研究模型内部算法的方法。", "用于定位能力来源、失效机制与潜在风险。", "它追踪内部因果结构，不只是生成一段自然语言理由。", ["mechanistic interpretability", "机理可解释性", "机制解释"], "alignment"],
  ["jailbreak", "Jailbreak", "越狱攻击", "通过特殊提示或交互诱导模型绕过安全策略的攻击。", "用于红队测试和评估防护策略。", "越狱针对模型行为边界，提示注入更常利用不可信外部指令。", ["越狱", "模型越狱"], "alignment"],
  ["prompt-injection", "Prompt injection", "提示注入", "把恶意指令藏在用户输入、网页或文档中，试图改变智能体行为的攻击。", "用于评估检索、浏览器和工具型智能体的安全。", "外部内容是数据，不应自动获得系统指令权限。", ["indirect prompt injection", "提示词注入", "间接提示注入"], "alignment"],
  ["data-poisoning", "Data poisoning", "数据投毒", "向训练、检索或记忆数据中植入恶意样本以操纵模型行为。", "用于分析供应链、知识库和持续学习风险。", "攻击发生在数据层，影响可能在很久后才被触发。", ["training data poisoning", "投毒攻击", "训练数据投毒"], "alignment"],
  ["model-collapse", "Model collapse", "模型坍塌", "反复用生成数据训练后，模型分布变窄并丢失真实世界多样性的现象。", "用于评估合成数据循环和数据生态风险。", "问题不是用了合成数据，而是错误与偏差不断自我放大。", ["模型崩塌", "递归训练退化"], "alignment"],
  ["bias", "Model bias", "模型偏差", "模型在不同群体、主题或场景中持续产生系统性差异的现象。", "用于公平性评测、数据治理和产品风险控制。", "偏差可能来自数据、目标、评测或部署环境。", ["ai bias", "算法偏见", "模型偏见"], "alignment"],
  ["toxicity", "Toxicity", "有害内容倾向", "模型生成侮辱、仇恨、骚扰或其他有害语言的倾向。", "用于内容安全训练和审核评测。", "它是可测风险维度之一，不代表全部安全问题。", ["toxic output", "毒性", "有毒输出"], "alignment"],

  ["rag", "Retrieval-augmented generation", "检索增强生成", "生成前先检索外部资料，再让模型依据检索结果作答的系统方式。", "用于企业知识库、时效信息和需要来源的问答。", "RAG 不把知识永久写进参数，而是在回答时临时取用。", ["retrieval augmented generation", "检索增强", "知识库问答"], "retrieval"],
  ["retrieval", "Retrieval", "信息检索", "从文档、数据库或其他集合中找出与查询最相关内容的过程。", "用于搜索、RAG、推荐和记忆召回。", "检索负责找证据，生成模型负责组织答案。", ["information retrieval", "检索", "召回"], "retrieval"],
  ["vector-database", "Vector database", "向量数据库", "专门存储向量并支持相似度搜索的数据库或检索系统。", "用于语义搜索、RAG、推荐和去重。", "它保存向量与元数据，不会自动保证检索内容正确。", ["vector db", "向量库"], "retrieval"],
  ["chunking", "Chunking", "文本切块", "把长文档切成适合嵌入、检索和放入上下文的小片段。", "用于构建 RAG 索引并控制证据粒度。", "块太小会丢上下文，太大又会引入噪声。", ["text chunking", "切片", "文档切分"], "retrieval"],
  ["reranking", "Reranking", "重排序", "对第一阶段召回的候选结果做更精细的相关性排序。", "用于提升真正送进模型的证据质量。", "召回追求不漏，重排追求把最好结果放前面。", ["re-ranking", "reranker", "重排"], "retrieval"],
  ["semantic-search", "Semantic search", "语义搜索", "根据含义相似度而不是只匹配字面词语进行搜索。", "适合问法多样、同义表达丰富的知识检索。", "语义相近不等于事实相关，仍需元数据和重排。", ["vector search", "语义检索", "向量搜索"], "retrieval"],
  ["keyword-search", "Keyword search", "关键词搜索", "依据词项出现、频率和字段规则匹配文档的搜索方式。", "适合专有名词、编号、精确短语和可解释过滤。", "它不理解深层语义，但精确匹配往往非常可靠。", ["lexical search", "关键词检索", "字面搜索"], "retrieval"],
  ["hybrid-search", "Hybrid search", "混合搜索", "组合关键词检索与向量语义检索，再融合排序结果。", "用于同时兼顾精确词项和语义相似性。", "混合不是简单相加，还要处理分数归一化和权重。", ["hybrid retrieval", "混合检索"], "retrieval"],
  ["knowledge-graph", "Knowledge graph", "知识图谱", "用实体、关系和属性把知识组织成图结构。", "用于关系查询、实体消歧、推理和 GraphRAG。", "图谱强调显式关系，向量库强调连续语义相似度。", ["kg", "知识网络"], "retrieval"],
  ["citation", "Citation", "引用溯源", "在回答中标明支撑某个结论的原始来源。", "用于核验事实、建立信任和回到完整上下文。", "链接存在不代表引用真的支持对应说法。", ["source citation", "来源引用", "引文"], "retrieval"],
  ["query-expansion", "Query expansion", "查询扩展", "把原始问题改写或补充成多个更易检索的查询。", "用于提高召回率、覆盖同义词和拆解复杂问题。", "扩展过多会引入偏题结果，需要与排序配合。", ["query rewriting", "查询改写", "检索扩展"], "retrieval"],
  ["hyde", "HyDE", "假设文档嵌入", "先生成一个假设答案文档，再用其向量去检索真实资料的方法。", "用于原始问题过短或难以直接匹配文档的场景。", "假设文档是检索桥梁，不应当直接当成事实依据。", ["hypothetical document embeddings", "假设文档"], "retrieval"],
  ["graphrag", "GraphRAG", "图检索增强生成", "结合知识图结构、社区摘要或关系遍历来检索并生成答案的方法。", "适合跨文档关系、全局主题和多跳问题。", "它比普通 RAG 多了图构建与维护成本。", ["graph rag", "图谱rag", "图增强检索"], "retrieval"],
  ["cache", "Cache", "缓存", "保存已计算结果，以便相同或相近请求直接复用。", "用于降低延迟、成本和重复工具调用。", "缓存提高效率，但必须处理过期、权限和个性化差异。", ["caching", "结果缓存"], "retrieval"],
  ["semantic-cache", "Semantic cache", "语义缓存", "对语义相近而非完全相同的请求复用已有结果。", "用于高频问答和相似检索请求的成本优化。", "相似问题未必有相同答案，需要严格的阈值和时效控制。", ["semantic caching", "语义级缓存"], "retrieval"],

  ["chain-of-thought", "Chain of thought", "思维链", "让模型生成中间推理步骤再给出答案的提示或训练范式。", "用于数学、逻辑和需要分解的复杂问题。", "中间文字能帮助推理，但不保证忠实反映模型内部过程。", ["cot", "chain-of-thought", "思维链推理"], "reasoning"],
  ["self-consistency", "Self-consistency", "自洽采样", "生成多条推理路径，并用多数一致答案作为最终结果的方法。", "用于提高有明确答案任务的推理稳定性。", "它靠多次采样投票，成本会随路径数量增加。", ["self consistency", "一致性投票", "自一致性"], "reasoning"],
  ["tree-of-thoughts", "Tree of thoughts", "思维树", "把推理表示成可扩展、评估和回退的分支搜索树。", "用于单一路径容易走错、需要探索多个方案的任务。", "它显式搜索多个思路，代价通常高于一次思维链。", ["tot", "tree of thought", "思维树搜索"], "reasoning"],
  ["beam-search", "Beam search", "束搜索", "每一步保留得分最高的若干候选序列并继续展开的搜索算法。", "用于机器翻译、语音识别和受控文本生成。", "它比贪心搜索看得更宽，但不保证找到全局最优。", ["beam decoding", "集束搜索"], "reasoning"],
  ["reflection", "Reflection", "反思机制", "让模型检查上一轮过程和结果，并形成下一轮改进信息。", "用于智能体循环、自我纠错和长期任务。", "反思只有在能发现真实错误并改变行动时才有价值。", ["self-reflection", "自我反思", "反思"], "reasoning"],
  ["critique", "Critique", "批评反馈", "针对候选结果明确指出问题、遗漏和改进方向。", "用于写作、代码、推理和候选答案复核。", "批评负责找问题，修订还需要把反馈落实到新结果。", ["self-critique", "批判", "评审反馈"], "reasoning"],
  ["debate", "AI debate", "智能体辩论", "让多个模型或角色提出并相互质疑不同结论的推理方法。", "用于暴露盲点、比较证据和提高复杂判断质量。", "辩论增加观点多样性，也可能放大共同偏差。", ["multi-agent debate", "模型辩论"], "reasoning"],
  ["task-decomposition", "Task decomposition", "任务拆解", "把复杂目标分成更小、可执行和可验证的子任务。", "用于规划、并行协作和长任务管理。", "好的拆解减少依赖混乱，而不是把一句话机械切碎。", ["decomposition", "任务分解", "问题拆解"], "reasoning"],
  ["scratchpad", "Scratchpad", "推理草稿区", "为模型保存中间计算、临时计划或未完成想法的工作空间。", "用于复杂推理和工具任务的状态维护。", "草稿是临时工作记忆，不等于长期记忆或最终答案。", ["reasoning scratchpad", "草稿纸", "中间草稿"], "reasoning"],
  ["structured-output", "Structured output", "结构化输出", "要求模型按照 JSON、表格或预定义字段返回结果。", "用于接入代码、工作流、数据库和工具调用。", "格式正确不代表内容正确，仍要验证字段语义。", ["json output", "结构化生成", "格式化输出"], "reasoning"],
  ["constrained-decoding", "Constrained decoding", "约束解码", "在生成过程中限制可选 token，使输出满足语法、词表或业务规则。", "用于可靠 JSON、代码语法和受控文本生成。", "它保证形式约束，不自动保证事实与业务逻辑。", ["grammar constrained decoding", "语法约束解码", "受限解码"], "reasoning"],
  ["speculative-decoding", "Speculative decoding", "推测解码", "先由小模型批量猜测 token，再由大模型并行验证以加速生成。", "用于降低大模型推理延迟而尽量保持相同输出分布。", "它减少等待时间，不是用小模型替代大模型质量。", ["speculative sampling", "投机解码", "推测采样"], "reasoning"],
  ["kv-cache", "KV cache", "键值缓存", "缓存注意力层中历史 token 的 Key 和 Value，避免生成时重复计算。", "用于显著加速自回归生成。", "它用显存换速度，并随序列长度增长。", ["key-value cache", "键值缓存", "注意力缓存"], "reasoning"],
  ["flash-attention", "FlashAttention", "闪存注意力", "通过更高效的数据搬运和分块计算精确注意力的算法。", "用于降低显存占用并加速长序列训练和推理。", "它优化实现效率，不改变注意力的数学结果。", ["flash attention", "闪电注意力"], "reasoning"],

  ["ocr", "OCR", "光学字符识别", "从图片、扫描件或界面截图中识别文字的技术。", "用于文档数字化、票据读取和视觉智能体。", "OCR 先把图像变成文字，后续理解仍需要语言或视觉模型。", ["optical character recognition", "文字识别", "图像文字识别"], "multimodal"],
  ["asr", "ASR", "自动语音识别", "把人类语音转换为文字序列的技术。", "用于语音助手、会议转写和字幕。", "ASR 负责听写，不等于理解说话者意图。", ["automatic speech recognition", "speech to text", "语音转文字"], "multimodal"],
  ["tts", "TTS", "文本转语音", "把文字内容合成为自然语音的技术。", "用于语音助手、有声内容和无障碍体验。", "TTS 负责说出来，语言模型负责决定说什么。", ["text to speech", "语音合成", "文字转语音"], "multimodal"],
  ["image-generation", "Image generation", "图像生成", "根据文字、图像或结构条件合成新图像的技术。", "用于创意设计、广告、游戏资产和图像编辑。", "生成效果受提示、训练数据、版权和一致性约束影响。", ["text to image", "文生图", "AI绘图"], "multimodal"],
  ["video-generation", "Video generation", "视频生成", "根据文字、图像或已有片段生成连续视频内容的技术。", "用于创意预览、广告、影视和交互模拟。", "难点不仅是单帧质量，还包括时间一致性和物理规律。", ["text to video", "文生视频", "AI视频"], "multimodal"],
  ["embodied-agent", "Embodied agent", "具身智能体", "在物理或模拟环境中通过感知和动作与世界交互的智能体。", "用于机器人、游戏角色和环境探索。", "具身强调行动会改变环境并产生真实反馈。", ["embodied ai", "具身智能", "具身代理"], "multimodal"],
  ["robotics-policy", "Robotics policy", "机器人策略", "把传感器观测映射为机器人动作或动作序列的决策模型。", "用于抓取、导航、操作和通用机器人控制。", "策略决定做什么，控制器负责精确执行动作。", ["robot policy", "机器人控制策略"], "multimodal"],
  ["visual-grounding", "Visual grounding", "视觉指代定位", "把文字中的对象或描述对应到图像中的具体区域。", "用于图像理解、机器人操作和 GUI 定位。", "它不仅识别类别，还要指出描述对应在哪里。", ["phrase grounding", "视觉定位", "指代表达理解"], "multimodal"],
  ["image-captioning", "Image captioning", "图像描述生成", "根据图像内容生成自然语言描述的任务。", "用于无障碍、媒体检索和视觉理解评测。", "好的描述应选择重要信息，而不是罗列所有像素。", ["image to text", "看图说话", "图像字幕"], "multimodal"],
  ["speech-to-speech", "Speech-to-speech", "语音到语音", "直接理解输入语音并生成语音回复的端到端交互方式。", "用于低延迟、保留语气和自然打断的语音助手。", "端到端语音交互不一定经过可见文字中间层。", ["s2s", "语音对语音", "端到端语音"], "multimodal"],

  ["workflow", "Workflow", "工作流", "把多个步骤、规则和责任按固定或条件顺序组织起来的执行流程。", "用于稳定重复业务和明确审计路径。", "工作流强调预定义流程，智能体则可以动态决定下一步。", ["agent workflow", "流程", "智能体工作流"], "operations"],
  ["orchestration", "Orchestration", "智能体编排", "协调模型、工具、记忆、任务和多个智能体执行顺序的系统能力。", "用于管理复杂依赖、并行任务和失败恢复。", "编排是系统层协调，不等于模型自己会规划。", ["agent orchestration", "编排", "任务编排"], "operations"],
  ["human-in-the-loop", "Human in the loop", "人在回路", "在关键步骤让人类提供判断、批准、纠正或补充信息的机制。", "用于高风险、低置信或不可逆操作。", "人工参与应放在真正需要判断的节点，而不是每一步都确认。", ["hitl", "human-in-loop", "人工介入", "人机协同"], "operations"],
  ["handoff", "Handoff", "任务移交", "把当前任务、上下文和责任从一个智能体或人转交给另一个执行者。", "用于专长切换、人工升级和跨团队流程。", "可靠移交必须同时传递状态、证据和下一步。", ["agent handoff", "转交", "移交"], "operations"],
  ["delegation", "Delegation", "任务委派", "由主智能体把明确子任务和权限交给另一个执行者。", "用于并行处理或调用专门能力。", "委派分出去的是责任边界，不是模糊地“帮我看看”。", ["agent delegation", "委派", "授权执行"], "operations"],
  ["sandbox", "Sandbox", "沙箱", "把代码或工具执行限制在隔离环境中的安全机制。", "用于减少文件、网络和系统权限带来的影响范围。", "沙箱降低风险，但仍需限制输入、输出和可访问资源。", ["sandboxing", "隔离环境", "安全沙箱"], "operations"],
  ["permissions", "Permissions", "权限控制", "规定智能体可以读取、修改或调用哪些资源的访问规则。", "用于最小权限、用户确认和敏感操作治理。", "有能力不等于有授权；权限应随任务范围收紧。", ["permissioning", "access control", "权限", "访问控制"], "operations"],
  ["observability", "Observability", "可观测性", "通过日志、指标、事件和追踪理解系统内部运行状态的能力。", "用于定位失败、评估成本和监控生产质量。", "可观测性提供证据，不能只靠最终回答猜过程。", ["agent observability", "系统可观测性"], "operations"],
  ["tracing", "Tracing", "链路追踪", "记录一次请求经过的模型、工具、步骤、耗时和结果。", "用于调试长链智能体与分析瓶颈。", "日志是离散记录，Trace 强调一次任务的完整因果链。", ["agent tracing", "追踪", "调用链"], "operations"],
  ["eval-harness", "Evaluation harness", "评测框架", "统一运行测试集、调用系统、收集结果并计算指标的工程框架。", "用于回归测试、模型比较和上线门槛。", "评测框架保证流程一致，指标设计仍需人工判断。", ["eval harness", "evaluation framework", "评测工具链"], "operations"],
  ["latency", "Latency", "延迟", "从请求发出到收到结果所经历的时间。", "用于衡量交互体验和服务性能。", "平均延迟可能掩盖长尾问题，通常还要看 P95、P99。", ["response time", "响应时间", "时延"], "operations"],
  ["throughput", "Throughput", "吞吐量", "单位时间内系统能处理的请求、token 或任务数量。", "用于容量规划和成本效率评估。", "吞吐高不代表单个请求延迟低，两者需要共同优化。", ["tokens per second", "tps", "吞吐"], "operations"],
  ["retry", "Retry", "重试机制", "调用失败后按策略再次执行同一操作的容错方式。", "用于处理临时网络、限流和服务波动。", "不是所有失败都应重试；不可逆操作尤其要避免重复执行。", ["retries", "重试"], "operations"],
  ["idempotency", "Idempotency", "幂等性", "同一操作执行一次或多次都产生相同最终效果的性质。", "用于安全重试支付、写入和工具调用。", "幂等让重试更安全，但需要请求标识或业务约束支持。", ["idempotent", "幂等"], "operations"],
  ["state-machine", "State machine", "状态机", "用有限状态和允许的转移规则描述流程行为的模型。", "用于可控工作流、审批和智能体执行约束。", "状态机牺牲部分自由度，换取可预测与可测试。", ["finite state machine", "fsm", "有限状态机"], "operations"],

  ["benchmark", "Benchmark", "基准测试", "用于在统一任务、数据和规则下比较模型或系统的测试集合。", "用于能力排名、研究进展和模型选型。", "榜单高分不等于你的真实业务也会更好。", ["基准", "benchmarking"], "evaluation"],
  ["evaluation", "Evaluation", "模型评测", "系统衡量模型质量、成本、安全和鲁棒性的过程。", "用于研发迭代、上线判断和持续监控。", "评测应围绕实际决策，而不只是堆积指标。", ["eval", "evals", "评估"], "evaluation"],
  ["eval-set", "Evaluation set", "评测集", "专门用于测试、而不参与训练的数据样本集合。", "用于比较版本和发现回归。", "评测集被反复针对性优化后，也可能失去代表性。", ["test set", "测试集", "验证集"], "evaluation"],
  ["accuracy", "Accuracy", "准确率", "预测正确的样本数占全部样本的比例。", "适合类别分布较均衡的分类任务。", "在极度不平衡数据中，高准确率可能毫无意义。", ["准确度", "正确率"], "evaluation"],
  ["precision", "Precision", "精确率", "被模型判为正例的样本中，真正为正例的比例。", "用于误报代价高的检测任务。", "Precision 关注报出来的有多准，Recall 关注真正目标找回多少。", ["查准率", "精准率"], "evaluation"],
  ["recall", "Recall", "召回率", "全部真实正例中，被模型成功找出的比例。", "用于漏报代价高的搜索、医疗和安全任务。", "召回高可能带来更多误报，需要和 Precision 权衡。", ["查全率", "指标召回"], "evaluation"],
  ["f1-score", "F1 score", "F1 分数", "Precision 与 Recall 的调和平均，用于综合衡量两者。", "适合正负样本不平衡且两类错误都重要的任务。", "F1 把两者同等看待，业务代价不同则需其他加权方式。", ["f1", "f1-score", "F1值"], "evaluation"],
  ["bleu", "BLEU", "BLEU 指标", "通过生成文本与参考译文的 n-gram 重合度评价机器翻译的指标。", "用于快速比较翻译系统。", "字面重合不等于语义和表达质量，不能单独代表人类体验。", ["bleu score", "双语评估替补"], "evaluation"],
  ["rouge", "ROUGE", "ROUGE 指标", "通过生成摘要与参考摘要的词片段重合度评价摘要质量的指标家族。", "用于自动摘要和文本生成评测。", "它偏好字面重合，可能低估正确但表达不同的答案。", ["rouge score", "摘要评测指标"], "evaluation"],
  ["pass-at-k", "Pass@k", "Pass@k 指标", "生成 k 个候选中至少有一个通过测试的概率估计。", "常用于代码生成和可自动验证任务。", "k 越大成功率通常越高，因此比较时必须使用相同预算。", ["pass at k", "pass@k", "k次通过率"], "evaluation"],

  ["artificial-intelligence", "Artificial intelligence", "人工智能", "让机器完成通常需要人类感知、学习、推理或决策能力的技术与研究领域。", "用于理解机器学习、生成式 AI 和智能体等技术的总范畴。", "AI 是一个领域，不是一种单独模型。", ["ai", "人工智能技术"], "foundation"],
  ["machine-learning", "Machine learning", "机器学习", "让系统从数据中学习规律，而不是为每种情况手写规则的方法集合。", "用于预测、分类、推荐、生成和自动决策。", "机器学习是实现 AI 的主要路径之一。", ["ml", "机器学习算法"], "foundation"],
  ["deep-learning", "Deep learning", "深度学习", "使用多层神经网络从数据中逐级学习表示的机器学习分支。", "用于图像、语音、语言和生成模型。", "“深”主要指网络层级多，不代表一定更聪明。", ["dl", "深层学习"], "foundation"],
  ["generative-ai", "Generative AI", "生成式 AI", "学习数据分布后生成新文本、图像、音频、视频或代码的 AI。", "用于内容创作、辅助设计、编程和交互产品。", "它创造新内容，区别于只做判断的判别式系统。", ["genai", "aigc", "生成式人工智能", "人工智能生成内容"], "foundation"],
  ["agi", "Artificial general intelligence", "通用人工智能", "能够跨领域学习、迁移并完成广泛智力任务的假设性通用 AI。", "用于讨论 AI 的长期能力目标与治理问题。", "AGI 尚无公认实现，也没有唯一评判标准。", ["agi", "general ai", "人工通用智能", "强人工智能"], "foundation"],
  ["narrow-ai", "Narrow AI", "狭义人工智能", "针对有限任务或领域设计、无法普遍迁移能力的 AI 系统。", "用于描述今天大多数分类、推荐和生成应用。", "能力很强也可能仍是专用系统。", ["ani", "weak ai", "弱人工智能", "专用人工智能"], "foundation"],
  ["neural-network", "Neural network", "神经网络", "由多层相连计算单元组成、通过权重变换输入的模型结构。", "用于学习复杂的非线性模式。", "神经网络借鉴神经元概念，但不是人脑的数字复制品。", ["artificial neural network", "ann", "人工神经网络"], "architecture"],
  ["algorithm", "Algorithm", "算法", "把输入转换为输出的一组明确计算步骤或规则。", "用于描述训练、搜索、排序和推理过程。", "模型是学到的表示，算法是解决问题的步骤。", ["算法流程", "计算方法"], "foundation"],
  ["model", "Model", "机器学习模型", "从训练数据中学到、用于对新输入进行预测或生成的数学表示。", "用于分类、回归、生成和决策。", "模型不是训练代码，也不是数据集本身。", ["ml model", "ai model", "模型"], "foundation"],
  ["feature", "Feature", "特征", "提供给模型、用于描述样本的可测量变量或表示。", "用于传统机器学习输入、分析和可解释性。", "特征是模型看到问题的方式。", ["input feature", "特征变量"], "foundation"],
  ["edge-ai", "Edge AI", "边缘 AI", "在手机、摄像头或其他终端本地运行模型的部署方式。", "用于低延迟、离线和隐私敏感场景。", "边缘 AI 少依赖云端，但受本地算力和电量限制。", ["on-device ai", "端侧ai", "端侧人工智能"], "operations"],
  ["ai-as-a-service", "AI as a service", "AI 即服务", "通过云接口按需提供模型或 AI 能力的服务模式。", "用于无需自建训练和推理基础设施的产品集成。", "调用服务省建设成本，但仍需管理数据、费用和供应商依赖。", ["aiaas", "maas", "model as a service", "模型即服务"], "operations"],
  ["gpu", "GPU", "图形处理器", "擅长大规模并行数值计算、广泛用于训练和运行神经网络的处理器。", "用于矩阵运算、模型训练和高吞吐推理。", "GPU 不只画图，也是现代 AI 的主要计算引擎。", ["graphics processing unit", "图形处理单元"], "operations"],
  ["tpu", "TPU", "张量处理单元", "为张量和机器学习计算专门设计的加速芯片。", "用于大规模训练与推理。", "TPU 更专用，GPU 通常生态和任务适应性更广。", ["tensor processing unit", "张量芯片"], "operations"],
  ["vram", "VRAM", "显存", "GPU 上用于保存模型权重、激活、缓存和批次数据的高速内存。", "用于判断模型能否加载以及可用批大小。", "显存容量常是本地运行大模型的第一道限制。", ["video memory", "gpu memory", "图形显存"], "operations"],
  ["cpu", "CPU", "中央处理器", "负责通用控制、逻辑和串行计算的核心处理器。", "用于数据预处理、程序编排和部分模型推理。", "CPU 更通用，GPU 更适合大量并行计算。", ["central processing unit", "中央处理单元"], "operations"],
  ["black-box", "Black box model", "黑盒模型", "内部决策过程难以由人直接理解或解释的模型。", "用于讨论模型审计、信任和可解释性风险。", "能看到输入输出，不等于能说明中间为什么这样算。", ["black box", "黑箱模型", "黑盒"], "alignment"],
  ["emergent-abilities", "Emergent abilities", "涌现能力", "模型规模或训练条件变化后显现、在较小系统中不明显的能力。", "用于研究规模扩展与能力跃迁。", "“突然出现”也可能受评测粒度和指标阈值影响。", ["emergence", "能力涌现", "涌现现象"], "evaluation"],

  ["supervised-learning", "Supervised learning", "监督学习", "使用带有正确答案标签的样本学习输入到输出映射的方法。", "用于分类、回归和结构化预测。", "训练时有答案，部署时预测新样本。", ["supervised ml", "有监督学习"], "training"],
  ["unsupervised-learning", "Unsupervised learning", "无监督学习", "在没有人工标签的数据中寻找结构、分组或表示的方法。", "用于聚类、降维和异常发现。", "没有标签不等于没有目标，算法仍依赖明确的优化准则。", ["unsupervised ml", "非监督学习"], "training"],
  ["semi-supervised-learning", "Semi-supervised learning", "半监督学习", "结合少量有标签数据与大量无标签数据进行训练的方法。", "用于标注昂贵但原始数据丰富的任务。", "关键是让无标签数据提供信号，而不是把猜测当真值。", ["semi supervised learning", "半监督式学习"], "training"],
  ["reinforcement-learning", "Reinforcement learning", "强化学习", "智能体通过与环境交互并最大化累计奖励来学习策略的方法。", "用于游戏、机器人、控制和模型对齐。", "强化学习从结果反馈中学行动，不要求每一步都有标准答案。", ["rl", "增强学习"], "training"],
  ["regularization", "Regularization", "正则化", "在训练目标或模型结构中加入约束，以减少对训练数据的过度适应。", "用于提升模型对新数据的泛化能力。", "正则化是在拟合能力和稳健性之间做约束。", ["regularisation", "正规化"], "training"],
  ["overfitting", "Overfitting", "过拟合", "模型过度记住训练数据细节，导致新数据表现下降的现象。", "用于诊断训练集好、验证集差的问题。", "训练分数高不一定真正学会了规律。", ["over-fitting", "过度拟合"], "evaluation"],
  ["underfitting", "Underfitting", "欠拟合", "模型能力、训练或特征不足，连训练数据中的主要规律也未学到。", "用于诊断训练和验证表现都偏低的问题。", "欠拟合是没学够，过拟合是记得太细。", ["under-fitting", "拟合不足"], "evaluation"],
  ["dropout", "Dropout", "随机失活", "训练时随机关闭部分神经元连接，以减少模型对固定路径的依赖。", "用于缓解神经网络过拟合。", "Dropout 只在训练中制造随机缺失，推理时通常关闭。", ["drop out", "随机丢弃"], "training"],
  ["cross-validation", "Cross-validation", "交叉验证", "轮流使用不同数据子集训练和验证，以估计模型泛化表现的方法。", "用于小数据选模和超参数比较。", "它减少一次划分的偶然性，但计算成本更高。", ["k-fold cross-validation", "k折交叉验证", "交叉检验"], "evaluation"],
  ["feature-engineering", "Feature engineering", "特征工程", "从原始数据构造、选择和变换更适合模型使用的特征。", "用于传统机器学习、风控和表格数据。", "好的特征把领域知识转成模型可学的信号。", ["特征构造", "特征处理"], "training"],
  ["ensemble-learning", "Ensemble learning", "集成学习", "组合多个模型的预测，以获得比单个模型更稳定的结果。", "用于分类、回归和模型融合。", "集成依靠模型差异互补，不是简单重复同一个错误。", ["model ensemble", "ensemble methods", "模型融合", "集成方法"], "architecture"],
  ["boosting", "Boosting", "提升方法", "按顺序训练弱学习器，让后续模型重点修正此前错误的集成方法。", "用于高性能表格数据分类和回归。", "Boosting 串行纠错，Bagging 更强调并行降低方差。", ["gradient boosting", "提升算法"], "training"],
  ["bias-variance-tradeoff", "Bias-variance tradeoff", "偏差—方差权衡", "在模型过于简单与对训练数据过度敏感之间取得平衡的问题。", "用于理解欠拟合、过拟合和模型复杂度。", "偏差高容易没学够，方差高容易不稳定。", ["bias variance tradeoff", "偏差方差权衡"], "evaluation"],
  ["federated-learning", "Federated learning", "联邦学习", "让多个设备或机构在数据不离开本地的情况下协同训练模型。", "用于隐私敏感、数据分散的场景。", "不集中原始数据能减少暴露，但不自动解决所有隐私风险。", ["federated ml", "联邦式学习"], "training"],
  ["meta-learning", "Meta-learning", "元学习", "让模型从多个任务中学习如何更快适应新任务的方法。", "用于少样本学习、快速适配和自动调参。", "它学习的是适应策略，而不只是某一任务答案。", ["learning to learn", "learning-to-learn", "学会学习"], "training"],
  ["multi-task-learning", "Multi-task learning", "多任务学习", "在一个模型中联合训练多个相关任务，共享部分表示。", "用于任务间知识迁移和提高数据利用率。", "任务互补会增益，任务冲突也可能互相拖累。", ["multitask learning", "联合任务学习"], "training"],
  ["classification", "Classification", "分类", "把输入分配到一个或多个离散类别的预测任务。", "用于垃圾邮件、图像类别和风险等级判断。", "分类输出类别，回归输出连续数值。", ["classifier", "分类任务"], "evaluation"],
  ["regression", "Regression", "回归", "根据输入预测连续数值或变量关系的统计与机器学习任务。", "用于价格、需求、时间和风险分数预测。", "回归通常回答“多少”，分类回答“哪一类”。", ["linear regression", "线性回归", "回归分析"], "evaluation"],
  ["clustering", "Clustering", "聚类", "根据相似性把没有标签的样本自动分成若干组。", "用于用户分群、主题发现和探索分析。", "聚类发现结构，但分组未必天然对应业务类别。", ["cluster analysis", "聚类分析"], "training"],
  ["decision-tree", "Decision tree", "决策树", "通过一系列条件分裂数据并得到预测结果的树形模型。", "用于分类、回归和可解释规则。", "每个分支像一次判断，路径组合成最终决定。", ["decision trees", "分类树", "回归树"], "architecture"],
  ["random-forest", "Random forest", "随机森林", "训练多棵带随机采样的决策树，再汇总其预测的集成模型。", "用于稳健的表格数据分类和回归。", "多棵有差异的树投票，通常比单棵树更不易过拟合。", ["random forests", "随机森林算法"], "architecture"],
  ["naive-bayes", "Naive Bayes", "朴素贝叶斯", "基于贝叶斯定理并假设特征条件独立的概率分类方法。", "用于文本分类、垃圾邮件和轻量基线。", "“朴素”来自强独立假设，但方法常常很实用。", ["naïve bayes", "朴素贝叶斯分类器"], "architecture"],
  ["support-vector-machine", "Support vector machine", "支持向量机", "寻找能以最大间隔分开类别的决策边界的监督学习模型。", "用于中小规模分类、回归和高维数据。", "它重点依赖边界附近的支持向量。", ["svm", "support vector machines", "支持向量机模型"], "architecture"],
  ["pca", "Principal component analysis", "主成分分析", "把相关高维变量投影到少数互相正交主成分的降维方法。", "用于可视化、压缩和去除冗余。", "PCA 保留最大方差，不保证保留最有业务意义的信息。", ["principal components", "主组件分析", "主成分降维"], "training"],
  ["time-series", "Time series", "时间序列", "按照时间顺序记录、相邻观测往往存在依赖的数据。", "用于需求、价格、设备和流量预测。", "时间顺序不能随意打乱，未来信息也不能泄露到过去。", ["time series data", "时序数据", "时间序列数据"], "foundation"],
  ["topic-modeling", "Topic modeling", "主题建模", "从大量文本中自动发现潜在主题及其词语分布的方法。", "用于文档探索、内容归类和趋势分析。", "主题是统计模式，不一定等于人工命名的真实概念。", ["topic model", "主题模型"], "retrieval"],

  ["cnn", "Convolutional neural network", "卷积神经网络", "通过卷积核提取局部空间特征的神经网络。", "用于图像识别、检测和视觉特征学习。", "CNN 共享局部滤波器，因此比全连接网络更适合图像。", ["convolutional neural network", "卷积网络"], "architecture"],
  ["rnn", "Recurrent neural network", "循环神经网络", "通过循环连接保存前序状态、处理序列数据的神经网络。", "用于早期语言、语音和时序建模。", "RNN 按顺序传递状态，长距离信息容易衰减。", ["recurrent neural network", "递归神经网络", "循环网络"], "architecture"],
  ["lstm", "Long short-term memory", "长短期记忆网络", "使用门控机制控制信息写入、保留和遗忘的 RNN 变体。", "用于长序列、语音和时间序列。", "LSTM 改善长依赖，但计算仍难像 Transformer 那样高度并行。", ["long short-term memory network", "长短期记忆", "lstm网络"], "architecture"],
  ["feed-forward-network", "Feed-forward neural network", "前馈神经网络", "信息从输入层单向流向输出层、不形成循环的网络结构。", "用于分类器、回归器和 Transformer 中的逐位置变换。", "前馈网络没有内部时间循环。", ["ffn", "feedforward network", "前馈网络"], "architecture"],
  ["autoencoder", "Autoencoder", "自编码器", "通过编码再重建输入来学习紧凑表示的神经网络。", "用于降维、去噪、异常检测和表示学习。", "它先压缩再复原，重建目标不等于真正理解。", ["auto-encoder", "自动编码器", "自编码网络"], "architecture"],
  ["gan", "Generative adversarial network", "生成对抗网络", "让生成器与判别器相互竞争来学习生成数据的模型框架。", "用于图像合成、风格迁移和数据增强。", "一个负责造，一个负责辨，竞争推动生成质量提高。", ["gans", "generative adversarial networks", "生成对抗网络gan"], "architecture"],
  ["activation-function", "Activation function", "激活函数", "对神经元加权结果施加非线性变换的函数。", "用于让多层网络表达复杂关系。", "没有非线性，多层线性变换仍等价于一层。", ["nonlinear activation", "非线性激活"], "architecture"],
  ["relu", "ReLU", "整流线性单元", "把负输入设为零、正输入保持不变的常用激活函数。", "用于加快深层网络训练并引入非线性。", "ReLU 简单高效，但神经元也可能长期停在零区间。", ["rectified linear unit", "线性整流函数"], "architecture"],
  ["pooling", "Pooling", "池化", "在局部区域汇总特征以缩小空间尺寸的操作。", "用于减少视觉网络计算并增强位置容忍度。", "池化压缩表示，也会丢失部分精确位置信息。", ["max pooling", "最大池化", "池化层"], "architecture"],
  ["convolution", "Convolution", "卷积", "让小型滤波器在输入上滑动并计算局部响应的操作。", "用于提取边缘、纹理和局部模式。", "相同卷积核在不同位置复用参数。", ["卷积操作", "卷积运算"], "architecture"],
  ["hidden-layer", "Hidden layer", "隐藏层", "位于输入与输出之间、负责逐级变换表示的神经网络层。", "用于学习从低级特征到高级抽象的内部表示。", "之所以叫隐藏层，是因为它不直接作为外部输入或结果。", ["hidden layers", "神经网络层", "隐含层"], "architecture"],

  ["auc", "AUC", "曲线下面积", "衡量分类器在不同阈值下区分正负样本能力的指标。", "用于二分类模型比较，常与 ROC 或 PR 曲线搭配。", "AUC 看排序区分能力，不直接给出最佳业务阈值。", ["area under the curve", "roc auc", "曲线下的面积"], "evaluation"],
  ["false-positive", "False positive", "假阳性", "真实为负例却被模型错误判为正例的结果。", "用于评估误报风险。", "假阳性是报错了，不是漏掉了。", ["fp", "误报", "第一类错误"], "evaluation"],
  ["false-negative", "False negative", "假阴性", "真实为正例却被模型错误判为负例的结果。", "用于评估漏报风险。", "假阴性是漏掉了，不是多报了。", ["fn", "漏报", "第二类错误"], "evaluation"],
  ["ground-truth", "Ground truth", "真实标注", "被视为评测或训练参考答案的可信观测或人工标签。", "用于计算模型误差和监督训练。", "Ground truth 也可能含标注误差，并非天然绝对正确。", ["groundtruth", "事实真相", "真值", "金标准"], "evaluation"],
  ["confidence-interval", "Confidence interval", "置信区间", "在给定统计方法与置信水平下，对未知量可能范围的区间估计。", "用于表达指标和实验结果的不确定性。", "置信区间比只报一个平均数更能说明估计稳定性。", ["ci", "置信区间估计"], "evaluation"],
  ["validation", "Validation", "模型验证", "用未参与参数更新的数据检查模型并辅助选择配置的阶段。", "用于调参、早停和版本选择。", "验证集帮助开发决策，测试集留作最终评估。", ["validation data", "验证阶段", "验证数据"], "evaluation"],
  ["uncertainty", "Uncertainty", "不确定性", "模型或数据对预测结果缺乏确定程度的量化描述。", "用于风险决策、置信区间和人工升级。", "模型给出高概率也可能校准不准。", ["predictive uncertainty", "预测不确定性"], "evaluation"],
  ["confusion-matrix", "Confusion matrix", "混淆矩阵", "按真实类别与预测类别统计正确和错误数量的表格。", "用于同时查看真阳性、假阳性、真阴性和假阴性。", "它把分类错误拆开，比单一准确率信息更完整。", ["error matrix", "误差矩阵", "混淆表"], "evaluation"],

  ["computer-vision", "Computer vision", "计算机视觉", "让计算机从图像和视频中提取、理解并使用信息的 AI 领域。", "用于识别、检测、分割、跟踪和视觉生成。", "计算机视觉不只是看见像素，还要把像素转成任务信息。", ["cv", "machine vision", "机器视觉"], "multimodal"],
  ["image-recognition", "Image recognition", "图像识别", "判断图像中包含哪些对象、场景或属性的视觉任务。", "用于相册分类、质量检测和内容审核。", "识别回答“是什么”，检测还要回答“在哪里”。", ["image classification", "图片识别"], "multimodal"],
  ["semantic-segmentation", "Semantic segmentation", "语义分割", "为图像中的每个像素分配语义类别的视觉任务。", "用于自动驾驶、医疗影像和遥感。", "它精确到像素，但同类别的不同实例可能不会分开。", ["pixel segmentation", "像素级分割"], "multimodal"],
  ["bounding-box", "Bounding box", "边界框", "用矩形坐标标记图像中目标位置的表示方式。", "用于目标检测、数据标注和视觉定位。", "边界框定位快，但不描述对象的精确轮廓。", ["bbox", "包围框", "检测框"], "multimodal"],
  ["deepfake", "Deepfake", "深度伪造", "利用生成模型合成或替换人脸、声音与动作的逼真伪造内容。", "用于媒体真实性检测与内容安全研究。", "技术也能用于创意，但冒充和误导风险很高。", ["deep fake", "深伪", "ai换脸"], "alignment"],
  ["clip", "CLIP", "图文对齐模型", "把图像和文本映射到同一语义空间进行匹配的对比学习模型。", "用于零样本图像分类、检索和多模态生成指导。", "CLIP 学会图文对应关系，不是完整的图像生成器。", ["contrastive language-image pre-training", "图文对比学习"], "multimodal"],
  ["nlp", "Natural language processing", "自然语言处理", "研究计算机如何分析、理解和生成人类语言的 AI 领域。", "用于搜索、翻译、问答、分类和对话。", "NLP 是领域，LLM 是其中一种重要技术路线。", ["natural language processing", "自然语言处理技术"], "foundation"],
  ["named-entity-recognition", "Named entity recognition", "命名实体识别", "从文本中找出人名、组织、地点、时间等实体并分类的任务。", "用于信息抽取、搜索和知识图谱。", "NER 先找到实体，再判断属于哪类。", ["ner", "entity recognition", "实体识别"], "retrieval"],
  ["sentiment-analysis", "Sentiment analysis", "情感分析", "识别文本表达的正负倾向、情绪或主观态度的任务。", "用于舆情、评论和客户反馈分析。", "情感受语境、反讽和文化影响，不能只看关键词。", ["opinion mining", "情绪分析", "情感倾向分析"], "foundation"],
  ["machine-translation", "Machine translation", "机器翻译", "自动把一种语言的文本或语音转换成另一种语言的技术。", "用于跨语言交流、本地化和字幕。", "好的翻译要保留含义、语气和上下文，而不只是逐词替换。", ["mt", "自动翻译"], "multimodal"],
  ["natural-language-generation", "Natural language generation", "自然语言生成", "把结构化数据、语义表示或模型状态转换成自然语言文本的过程。", "用于报告、对话、摘要和内容生成。", "NLG 负责组织语言，事实仍取决于输入与验证。", ["nlg", "语言生成", "文本生成"], "foundation"],
  ["recommendation-system", "Recommendation system", "推荐系统", "根据用户、内容和行为信号预测哪些项目最相关的系统。", "用于商品、视频、音乐和信息流排序。", "推荐优化的是相关性与目标，不等于用户真正需要。", ["recommender system", "推荐引擎", "个性化推荐"], "retrieval"],
  ["collaborative-filtering", "Collaborative filtering", "协同过滤", "利用相似用户或相似项目的历史行为进行推荐的方法。", "用于用户—物品交互数据丰富的推荐场景。", "它依赖群体行为，冷启动时信号不足。", ["cf", "协作过滤"], "retrieval"],
  ["learning-to-rank", "Learning to rank", "排序学习", "用机器学习直接优化搜索或推荐结果顺序的方法。", "用于信息检索、广告和推荐排序。", "它学习谁排前面，不只是判断相关或不相关。", ["ltr", "learning-to-rank", "机器学习排序"], "retrieval"],
  ["semantic-web", "Semantic web", "语义网", "用可机器理解的实体、关系和标准描述网络数据的理念与技术体系。", "用于知识图谱、数据互联和结构化查询。", "语义网强调明确关系，普通网页主要面向人阅读。", ["web of data", "语义互联网"], "retrieval"],
  ["rpa", "Robotic process automation", "机器人流程自动化", "用软件机器人按固定规则操作界面和业务系统的自动化方式。", "用于录入、对账、搬运和重复办公流程。", "RPA 擅长稳定规则，智能体更擅长处理动态判断。", ["robotic process automation", "流程自动化", "软件机器人"], "operations"],

  ["turing-test", "Turing test", "图灵测试", "通过文字交互判断机器表现是否能与人类难以区分的思想实验。", "用于讨论机器智能的外在表现。", "通过模仿人类对话不等于具备所有形式的智能。", ["imitation game", "图灵测验"], "evaluation"],
  ["responsible-ai", "Responsible AI", "负责任的人工智能", "在 AI 全生命周期落实公平、透明、安全、隐私和问责的原则与实践。", "用于产品治理、风险审查和组织制度。", "它不是一项单独算法，而是一套持续治理方法。", ["rai", "responsible artificial intelligence", "可信人工智能"], "alignment"],
  ["ai-safety", "AI safety", "人工智能安全", "研究如何减少 AI 系统造成事故、滥用、失控和长期风险的领域。", "用于安全训练、评测、权限和治理设计。", "安全既包括今天的产品风险，也包括更长期的系统性风险。", ["artificial intelligence safety", "模型安全", "ai安全"], "alignment"],
  ["swarm-intelligence", "Swarm intelligence", "群体智能", "通过多个简单个体的局部协作产生整体问题求解能力的方法。", "用于优化、机器人群体和分布式搜索。", "个体规则可以简单，整体行为却可能很复杂。", ["collective intelligence", "集群智能"], "operations"],
  ["value-function", "Value function", "价值函数", "估计某个状态或状态—动作组合未来累计回报的函数。", "用于强化学习策略评估和决策。", "奖励是即时反馈，价值是对未来总回报的预期。", ["state value", "action value", "状态价值函数"], "training"],
  ["reward-function", "Reward function", "奖励函数", "把环境结果映射为奖励信号、定义智能体优化方向的规则。", "用于强化学习、对齐和行为塑造。", "奖励写错会让系统把指标做高，却偏离真实目标。", ["reward signal", "回报函数", "奖励机制"], "training"],
];

export const glossaryEntries = rawEntries.map(
  ([key, term, title, definition, use, takeaway, aliases, category]) => ({
    key,
    term,
    title,
    definition,
    use,
    takeaway,
    aliases,
    category,
  }),
);
